name: Check icons

on:
  workflow_call:
    inputs:
      app-repository:
        required: false
        default: ${{ github.repository }}
        type: string
      repo-name:
        required: false
        default: ${{ github.event.repository.name }}
        type: string
      run_for_devices:
        required: true
        type: string

jobs:
  check_icons:
    name: Check icons
    runs-on: ubuntu-latest

    steps:
      - name: Clone workflows repository
        uses: actions/checkout@v3
        with:
          repository: LedgerHQ/ledger-app-workflows
          path: ./ledger-app-workflows

      - name: Clone app repository
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.app-repository }}
          path: app-repository
          submodules: true

      - name: Run script
        run: bash ./ledger-app-workflows/scripts/check_icons.sh app-repository ${{ inputs.repo-name }} '${{ inputs.run_for_devices }}'
