name: Check readme

on:
  workflow_call:
    inputs:
      ledger-app-workflows_ref:
        description: 'The current reference in use for the ledger-app-workflow repository'
        required: true
        type: string
      app-repository:
        description: 'The URL of the app repository to check. Defaults to the workflow caller repository URL'
        required: false
        default: ${{ github.repository }}
        type: string
      repo-name:
        description: 'The name of the app repository to check. Defaults to the workflow caller repository name'
        required: false
        default: ${{ github.event.repository.name }}
        type: string

jobs:
  check_readme:
    name: Check readme
    runs-on: ubuntu-latest

    steps:
      - name: Clone workflows repository
        uses: actions/checkout@v3
        with:
          repository: ftheirs/ledger-app-workflows
          path: ./ledger-app-workflows
          ref: ${{ inputs.ledger-app-workflows_ref }}

      - name: Clone app repository
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.app-repository }}
          path: app-repository
          submodules: recursive

      - name: Run script
        run: bash ./ledger-app-workflows/scripts/check_readme.sh app-repository ${{ inputs.repo-name }}
